import {
  MenuCategory,
  MenuItem,
  ModifierGroup,
  ModifierOption,
  ItemModifierLink,
  DiningTable,
  TableSection,
  Order,
  OrderItem,
  InventoryItem,
  Recipe,
  RecipeIngredient,
  Supplier,
  Employee,
  Customer,
  Coupon,
  SettingRecord,
  Shift,
  CashDrawer
} from './schema';

const NOW = new Date().toISOString();

// ==========================================
// 1. MENU CATEGORIES
// ==========================================
export const INITIAL_CATEGORIES: MenuCategory[] = [
  {
    id: 'cat-appetizers',
    nameAr: 'المقبلات والشوربات الفاخرة',
    nameEn: 'Luxury Appetizers & Soups',
    descriptionAr: 'تشكيلة مختارة من المقبلات الشرقية والغربية الساخنة والباردة',
    descriptionEn: 'Selection of hot and cold oriental and western starters',
    icon: 'Soup',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
    sortOrder: 1,
    isActive: true,
    color: '#E07A5F',
    printerTarget: 'salad_cold',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cat-grills-mains',
    nameAr: 'المشاوي الملكية والأطباق الرئيسية',
    nameEn: 'Royal Grills & Prime Cuts',
    descriptionAr: 'لحوم بلدية طازجة ومشويات على الفحم الطبيعي وخيرات البحر',
    descriptionEn: 'Charcoal grilled fresh meats and prime cuts',
    icon: 'Flame',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
    sortOrder: 2,
    isActive: true,
    color: '#D62828',
    printerTarget: 'grill',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cat-seafood',
    nameAr: 'المأكولات البحرية الطازجة',
    nameEn: 'Fresh Seafood Specialties',
    descriptionAr: 'صيد اليوم من الأسماك وثمار البحر المطهوة بخلطاتنا الحصرية',
    descriptionEn: 'Catch of the day fish and premium seafood delights',
    icon: 'Fish',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
    sortOrder: 3,
    isActive: true,
    color: '#0077B6',
    printerTarget: 'main_kitchen',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cat-pasta-pizza',
    nameAr: 'الباستا والبيتزا الإيطالية',
    nameEn: 'Artisan Pasta & Woodfired Pizza',
    descriptionAr: 'باستا محضرة يدويًا وبيتزا نابولية في فرن الحطب الأصيل',
    descriptionEn: 'Handcrafted pasta and authentic wood-fired Neapolitan pizza',
    icon: 'UtensilsCrossed',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    sortOrder: 4,
    isActive: true,
    color: '#F4A261',
    printerTarget: 'bakery',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cat-desserts',
    nameAr: 'الحلويات الشرقية والغربية',
    nameEn: 'Signature Desserts',
    descriptionAr: 'كنافة نابلسية، أم علي، سوفليه الشوكولاتة والتشيز كيك المميز',
    descriptionEn: 'Gourmet sweets, Arabic Kunafa, and artisan pastries',
    icon: 'Cake',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    sortOrder: 5,
    isActive: true,
    color: '#9B5DE5',
    printerTarget: 'dessert',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cat-beverages',
    nameAr: 'المشروبات والكوكتيلات والقهوة المختصة',
    nameEn: 'Specialty Coffee & Beverages',
    descriptionAr: 'عصائر طبيعية منعشة، موهيتو منعش، وقهوة مختصة مقطرة',
    descriptionEn: 'Fresh mocktails, cold juices, and specialty brews',
    icon: 'Coffee',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    sortOrder: 6,
    isActive: true,
    color: '#2A9D8F',
    printerTarget: 'beverages',
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ==========================================
// 2. MENU ITEMS
// ==========================================
export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Appetizers
  {
    id: 'item-mixed-mezze',
    categoryId: 'cat-appetizers',
    nameAr: 'تشكيلة المزة الشامية الملكية',
    nameEn: 'Royal Levantine Mezze Platter',
    descriptionAr: 'حمص بالصنوبر واللحم، متبل باذنجان مدخن، تبولة بزيت الزيتون البكر، ورق عنب بدبس الرمان وكبة مقرمشة',
    descriptionEn: 'Hummus with pine nuts & meat, smoked mutabbal, fresh tabbouleh, stuffed vine leaves & crispy kibbeh',
    price: 68.0,
    costPrice: 18.5,
    taxRate: 0.15,
    barcode: '6281001',
    sku: 'APP-MEZZE-01',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
    calories: 520,
    preparationTimeMinutes: 8,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: ['sesame', 'nuts', 'gluten'],
    kitchenStation: 'salad_cold',
    sortOrder: 1,
    soldCount: 342,
    bcgCategory: 'star',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-truffle-soup',
    categoryId: 'cat-appetizers',
    nameAr: 'شوربة الفطر البري وزيت الكمأة',
    nameEn: 'Wild Mushroom & Truffle Cream Soup',
    descriptionAr: 'مزيج فاخر من الفطر الطازج مع كريمة الطهي الفرنسية وقطرات زيت الكمأة الأسود وخبز الكروتون المحمص',
    descriptionEn: 'Velvety forest mushroom soup infused with black truffle oil and artisanal garlic croutons',
    price: 45.0,
    costPrice: 11.0,
    taxRate: 0.15,
    barcode: '6281002',
    sku: 'APP-SOUP-02',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
    calories: 340,
    preparationTimeMinutes: 10,
    isAvailable: true,
    isFeatured: false,
    isRecommended: true,
    allergens: ['dairy', 'gluten'],
    kitchenStation: 'main_kitchen',
    sortOrder: 2,
    soldCount: 215,
    bcgCategory: 'star',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-dynamite-shrimp',
    categoryId: 'cat-appetizers',
    nameAr: 'داينمايت شرمب مقرمش',
    nameEn: 'Crispy Dynamite Shrimp',
    descriptionAr: 'روبيان تيمبورا مقرمش مغطى بصلصة الديناميت الكريمية الحارة مع البصل الأخضر والسمسم المحمص',
    descriptionEn: 'Golden crispy fried jumbo shrimp glazed with spicy Japanese creamy sauce and scallions',
    price: 58.0,
    costPrice: 19.0,
    taxRate: 0.15,
    barcode: '6281003',
    sku: 'APP-SHRIMP-03',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
    calories: 460,
    preparationTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: ['crustaceans', 'eggs', 'mustard', 'sesame'],
    kitchenStation: 'fryer',
    sortOrder: 3,
    soldCount: 480,
    bcgCategory: 'star',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Grills & Mains
  {
    id: 'item-mixed-grill-platter',
    categoryId: 'cat-grills-mains',
    nameAr: 'مشكل مشاوي السلطان المميز',
    nameEn: 'Sultan Special Mixed Grill Platter',
    descriptionAr: 'أوصال غنم نعيمي بلدي، شيش طاووق متبل، كباب بالزعفران، ريش غنم مشوية مع خضار مشوية وخبز البيواز وصلصة الثوم',
    descriptionEn: 'Prime lamb kebab, tender beef cubes, saffron shish tawook & lamb cutlets served with grilled vegetables & biwaz bread',
    price: 145.0,
    costPrice: 48.0,
    taxRate: 0.15,
    barcode: '6281004',
    sku: 'MAIN-GRILL-01',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
    calories: 980,
    preparationTimeMinutes: 20,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: ['dairy', 'gluten'],
    kitchenStation: 'grill',
    sortOrder: 1,
    soldCount: 650,
    bcgCategory: 'cash_cow',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-wagyu-ribeye',
    categoryId: 'cat-grills-mains',
    nameAr: 'ستيك واغيو ريب آي (درجة A5)',
    nameEn: 'Japanese Wagyu Ribeye Steak A5 (300g)',
    descriptionAr: 'شريحة لحم واغيو يابانية فاخرة 300 غرام مع زبدة الأعشاب العطرية، بطاطس مهروسة بالكمأة وخضار سوتيه',
    descriptionEn: 'Melt-in-your-mouth 300g A5 Wagyu Ribeye served with truffle mashed potatoes, grilled asparagus & peppercorn jus',
    price: 320.0,
    costPrice: 125.0,
    taxRate: 0.15,
    barcode: '6281005',
    sku: 'MAIN-STEAK-02',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    calories: 840,
    preparationTimeMinutes: 22,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: ['dairy'],
    kitchenStation: 'grill',
    sortOrder: 2,
    soldCount: 145,
    bcgCategory: 'star',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-lamb-ouzi',
    categoryId: 'cat-grills-mains',
    nameAr: 'موزات غنم محمرة مع أرز الأوزي المعطر',
    nameEn: 'Slow-Cooked Lamb Shank with Ouzi Rice',
    descriptionAr: 'موزة غنم طازجة مطهوة ببطء لمدة 6 ساعات حتى الذوبان، تقدم مع أرز الأوزي الشرقي بالمكسرات والزبيب وصلصة الدقوس',
    descriptionEn: '6-hour braised tender lamb shank atop spiced oriental fragrant rice garnished with roasted almonds, cashews and daqoos',
    price: 110.0,
    costPrice: 34.0,
    taxRate: 0.15,
    barcode: '6281006',
    sku: 'MAIN-OUZI-03',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    calories: 1050,
    preparationTimeMinutes: 15,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: ['nuts'],
    kitchenStation: 'main_kitchen',
    sortOrder: 3,
    soldCount: 520,
    bcgCategory: 'cash_cow',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Seafood
  {
    id: 'item-grilled-salmon',
    categoryId: 'cat-seafood',
    nameAr: 'فيليه السلمون النرويجي بصلصة الليمون والشبت',
    nameEn: 'Pan-Seared Norwegian Salmon Fillet',
    descriptionAr: 'سلمون طازج مشوي مع صلصة الليمون والكريمة والشبت الطازج، يقدم مع أرز الزعفران وهليون مشوي',
    descriptionEn: 'Crispy skin fresh salmon fillet topped with creamy dill-lemon sauce, saffron basmati rice & grilled baby asparagus',
    price: 125.0,
    costPrice: 42.0,
    taxRate: 0.15,
    barcode: '6281007',
    sku: 'SEA-SALMON-01',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=80',
    calories: 620,
    preparationTimeMinutes: 18,
    isAvailable: true,
    isFeatured: false,
    isRecommended: true,
    allergens: ['fish', 'dairy'],
    kitchenStation: 'main_kitchen',
    sortOrder: 1,
    soldCount: 290,
    bcgCategory: 'cash_cow',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-lobster-thermidor',
    categoryId: 'cat-seafood',
    nameAr: 'استاكوزا ثيرميدور بالجبن والأعشاب',
    nameEn: 'Classic Lobster Thermidor',
    descriptionAr: 'استاكوزا بحرية محشوة بلحم الاستاكوزا الطري مع صوص الماسترد، جبنة الغرويير الذائبة وفطر البورشيني',
    descriptionEn: 'Whole lobster tail cooked in rich creamy mustard & mushroom sauce, gratinated with Gruyère cheese',
    price: 240.0,
    costPrice: 95.0,
    taxRate: 0.15,
    barcode: '6281008',
    sku: 'SEA-LOBSTER-02',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
    calories: 780,
    preparationTimeMinutes: 25,
    isAvailable: true,
    isFeatured: true,
    isRecommended: false,
    allergens: ['crustaceans', 'dairy', 'mustard'],
    kitchenStation: 'main_kitchen',
    sortOrder: 2,
    soldCount: 88,
    bcgCategory: 'question_mark',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Pasta & Pizza
  {
    id: 'item-truffle-tagliatelle',
    categoryId: 'cat-pasta-pizza',
    nameAr: 'تاليياتيلي الكمأة البرية وجبن البارميزان',
    nameEn: 'Fresh Black Truffle Tagliatelle',
    descriptionAr: 'باستا طازجة محضرة يدويًا مع كريمة الكمأة السوداء، شرائح الكمأة الطازجة وجبن البارميجانو ريجيانو المعتق 24 شهرًا',
    descriptionEn: 'Handmade fresh egg pasta tossed in black truffle butter, fresh summer truffle shavings & 24-month aged Parmigiano Reggiano',
    price: 95.0,
    costPrice: 26.0,
    taxRate: 0.15,
    barcode: '6281009',
    sku: 'PASTA-TRUFFLE-01',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    calories: 710,
    preparationTimeMinutes: 14,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: ['dairy', 'eggs', 'gluten'],
    kitchenStation: 'bakery',
    sortOrder: 1,
    soldCount: 380,
    bcgCategory: 'star',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-neapolitan-burrata-pizza',
    categoryId: 'cat-pasta-pizza',
    nameAr: 'بيتزا نابولية بالبوراتا والبيستو الطازج',
    nameEn: 'Artisan Burrata & Pesto Neapolitan Pizza',
    descriptionAr: 'عجينة متخمرة 48 ساعة، صلصة سان مارزانو، كرة بوراتا إيطالية كاملة، صنوبر محمص وريحان طازج',
    descriptionEn: '48h fermented sourdough, San Marzano tomato sauce, whole fresh burrata cheese, pesto drops & baby basil',
    price: 82.0,
    costPrice: 21.0,
    taxRate: 0.15,
    barcode: '6281010',
    sku: 'PIZZA-BURRATA-02',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    calories: 890,
    preparationTimeMinutes: 12,
    isAvailable: true,
    isFeatured: false,
    isRecommended: true,
    allergens: ['dairy', 'gluten', 'nuts'],
    kitchenStation: 'bakery',
    sortOrder: 2,
    soldCount: 420,
    bcgCategory: 'cash_cow',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Desserts
  {
    id: 'item-royal-kunafa',
    categoryId: 'cat-desserts',
    nameAr: 'كنافة نابلسية بالجبن العكاوي والفستق الحلبي',
    nameEn: 'Royal Nabulsi Cheese Kunafa',
    descriptionAr: 'كنافة خشنة ذهبية مقرمشة محشوة بالجبن العكاوي البلدي المنسول، تسقى بالقطر العطري بماء الزهر ورشة فستق حلبي فاخر',
    descriptionEn: 'Crispy golden shredded filo pastry stuffed with gooey Akkawi cheese, blossom syrup & roasted Aleppo pistachios',
    price: 48.0,
    costPrice: 12.0,
    taxRate: 0.15,
    barcode: '6281011',
    sku: 'DES-KUNAFA-01',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    calories: 590,
    preparationTimeMinutes: 12,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: ['dairy', 'gluten', 'nuts'],
    kitchenStation: 'dessert',
    sortOrder: 1,
    soldCount: 510,
    bcgCategory: 'cash_cow',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-san-sebastian',
    categoryId: 'cat-desserts',
    nameAr: 'تشيز كيك سان سيباستيان المحروقة مع صوص الشوكولاتة البلجيكية',
    nameEn: 'Basque Burnt Cheesecake with Belgian Chocolate',
    descriptionAr: 'تشيز كيك إسبانية بقوام كريمي حريري من الداخل مع طبقة كراميل محروقة مميزة وصوص شوكولاتة بلجيكية بلجيكية ساخنة',
    descriptionEn: 'Ultra-creamy burnt Basque cheesecake served warm with molten Belgian chocolate sauce',
    price: 52.0,
    costPrice: 14.5,
    taxRate: 0.15,
    barcode: '6281012',
    sku: 'DES-SANSEB-02',
    image: 'https://images.unsplash.com/photo-1508737027454-e6454ef45afd?auto=format&fit=crop&w=600&q=80',
    calories: 640,
    preparationTimeMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    isRecommended: true,
    allergens: ['dairy', 'eggs', 'gluten'],
    kitchenStation: 'dessert',
    sortOrder: 2,
    soldCount: 390,
    bcgCategory: 'star',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Beverages
  {
    id: 'item-passion-mojito',
    categoryId: 'cat-beverages',
    nameAr: 'موهيتو الباشن فروت والنعناع المنعش',
    nameEn: 'Passion Fruit & Fresh Mint Artisan Mojito',
    descriptionAr: 'لب الباشن فروت الطبيعي مع الليمون، أوراق النعناع الطازجة، الصودا الفوارة وقطع الثلج المجروش',
    descriptionEn: 'Tropical passion fruit pulp, crushed fresh mint, lime wedges, sparkling soda & crushed ice',
    price: 34.0,
    costPrice: 6.0,
    taxRate: 0.15,
    barcode: '6281013',
    sku: 'BEV-MOJITO-01',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    calories: 160,
    preparationTimeMinutes: 5,
    isAvailable: true,
    isFeatured: true,
    isRecommended: true,
    allergens: [],
    kitchenStation: 'beverages',
    sortOrder: 1,
    soldCount: 680,
    bcgCategory: 'star',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-v60-coffee',
    categoryId: 'cat-beverages',
    nameAr: 'قهوة V60 مختصة (محصول إثيوبي مجفف)',
    nameEn: 'Specialty V60 Pour-Over Coffee (Ethiopian Yirgacheffe)',
    descriptionAr: 'قهوة مقطرة يدويًا بإيحاءات الفواكه المجففة والياسمين وقوام حريري متوازن',
    descriptionEn: 'Single origin Ethiopian coffee beans with jasmine and dried berry tasting notes',
    price: 28.0,
    costPrice: 4.5,
    taxRate: 0.15,
    barcode: '6281014',
    sku: 'BEV-V60-02',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
    calories: 5,
    preparationTimeMinutes: 6,
    isAvailable: true,
    isFeatured: false,
    isRecommended: true,
    allergens: [],
    kitchenStation: 'beverages',
    sortOrder: 2,
    soldCount: 430,
    bcgCategory: 'cash_cow',
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ==========================================
// 3. MODIFIER GROUPS & OPTIONS
// ==========================================
export const INITIAL_MODIFIER_GROUPS: ModifierGroup[] = [
  {
    id: 'mod-steak-doneness',
    nameAr: 'درجة استواء اللحم',
    nameEn: 'Meat Doneness',
    minSelection: 1,
    maxSelection: 1,
    isRequired: true,
    allowMultipleQuantity: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mod-sauces',
    nameAr: 'الصلصات الإضافية',
    nameEn: 'Gourmet Sauces',
    minSelection: 0,
    maxSelection: 3,
    isRequired: false,
    allowMultipleQuantity: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mod-extra-toppings',
    nameAr: 'الإضافات الخاصة',
    nameEn: 'Extra Toppings',
    minSelection: 0,
    maxSelection: 4,
    isRequired: false,
    allowMultipleQuantity: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mod-drink-size',
    nameAr: 'حجم المشروب',
    nameEn: 'Drink Size',
    minSelection: 1,
    maxSelection: 1,
    isRequired: true,
    allowMultipleQuantity: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const INITIAL_MODIFIER_OPTIONS: ModifierOption[] = [
  // Doneness
  {
    id: 'opt-medium-rare',
    groupId: 'mod-steak-doneness',
    nameAr: 'نصف استواء وردي (Medium Rare)',
    nameEn: 'Medium Rare',
    price: 0,
    costPrice: 0,
    isDefault: true,
    isAvailable: true,
    sortOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'opt-medium',
    groupId: 'mod-steak-doneness',
    nameAr: 'متوسط الاستواء (Medium)',
    nameEn: 'Medium',
    price: 0,
    costPrice: 0,
    isDefault: false,
    isAvailable: true,
    sortOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'opt-well-done',
    groupId: 'mod-steak-doneness',
    nameAr: 'كامل الاستواء (Well Done)',
    nameEn: 'Well Done',
    price: 0,
    costPrice: 0,
    isDefault: false,
    isAvailable: true,
    sortOrder: 3,
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Sauces
  {
    id: 'opt-peppercorn-sauce',
    groupId: 'mod-sauces',
    nameAr: 'صلصة الفلفل الأسود والزعتر البري',
    nameEn: 'Black Peppercorn Sauce',
    price: 8.0,
    costPrice: 1.5,
    isDefault: false,
    isAvailable: true,
    sortOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'opt-mushroom-cream-sauce',
    groupId: 'mod-sauces',
    nameAr: 'صلصة فطر البورشيني الكريمية',
    nameEn: 'Porcini Mushroom Cream Sauce',
    price: 10.0,
    costPrice: 2.2,
    isDefault: false,
    isAvailable: true,
    sortOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'opt-truffle-butter',
    groupId: 'mod-sauces',
    nameAr: 'زبدة الكمأة السوداء الذائبة',
    nameEn: 'Melted Black Truffle Butter',
    price: 14.0,
    costPrice: 3.5,
    isDefault: false,
    isAvailable: true,
    sortOrder: 3,
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Extra toppings
  {
    id: 'opt-extra-cheese',
    groupId: 'mod-extra-toppings',
    nameAr: 'جبن موزاريلا وبوراتا إضافي',
    nameEn: 'Extra Mozzarella & Burrata',
    price: 15.0,
    costPrice: 4.0,
    isDefault: false,
    isAvailable: true,
    sortOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'opt-grilled-prawns',
    groupId: 'mod-extra-toppings',
    nameAr: 'حبتين جمبري جامبو مشوي',
    nameEn: '2x Grilled Jumbo Tiger Prawns',
    price: 28.0,
    costPrice: 9.0,
    isDefault: false,
    isAvailable: true,
    sortOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Drink Size
  {
    id: 'opt-drink-regular',
    groupId: 'mod-drink-size',
    nameAr: 'حجم عادي (Regular 350ml)',
    nameEn: 'Regular (350ml)',
    price: 0,
    costPrice: 0,
    isDefault: true,
    isAvailable: true,
    sortOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'opt-drink-large',
    groupId: 'mod-drink-size',
    nameAr: 'حجم كبير (Large 500ml)',
    nameEn: 'Large (500ml)',
    price: 6.0,
    costPrice: 1.2,
    isDefault: false,
    isAvailable: true,
    sortOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const INITIAL_ITEM_MODIFIER_LINKS: ItemModifierLink[] = [
  { id: 'link-1', menuItemId: 'item-wagyu-ribeye', modifierGroupId: 'mod-steak-doneness', sortOrder: 1, createdAt: NOW, updatedAt: NOW },
  { id: 'link-2', menuItemId: 'item-wagyu-ribeye', modifierGroupId: 'mod-sauces', sortOrder: 2, createdAt: NOW, updatedAt: NOW },
  { id: 'link-3', menuItemId: 'item-mixed-grill-platter', modifierGroupId: 'mod-sauces', sortOrder: 1, createdAt: NOW, updatedAt: NOW },
  { id: 'link-4', menuItemId: 'item-neapolitan-burrata-pizza', modifierGroupId: 'mod-extra-toppings', sortOrder: 1, createdAt: NOW, updatedAt: NOW },
  { id: 'link-5', menuItemId: 'item-passion-mojito', modifierGroupId: 'mod-drink-size', sortOrder: 1, createdAt: NOW, updatedAt: NOW },
];

// ==========================================
// 4. SECTIONS & DINING TABLES
// ==========================================
export const INITIAL_SECTIONS: TableSection[] = [
  { id: 'sec-main', nameAr: 'الصالة الملكية الرئيسية', nameEn: 'Royal Main Dining Room', floor: 1, isActive: true, color: '#3B82F6', sortOrder: 1, createdAt: NOW, updatedAt: NOW },
  { id: 'sec-terrace', nameAr: 'التراس والشرفة الخارجية', nameEn: 'Open Air Terrace Lounge', floor: 1, isActive: true, color: '#10B981', sortOrder: 2, createdAt: NOW, updatedAt: NOW },
  { id: 'sec-vip', nameAr: 'أجنحة العائلات VIP', nameEn: 'VIP Private Family Suites', floor: 2, isActive: true, color: '#8B5CF6', sortOrder: 3, createdAt: NOW, updatedAt: NOW },
];

export const INITIAL_TABLES: DiningTable[] = [
  { id: 'tbl-m1', tableNumber: 'T-01', sectionId: 'sec-main', capacity: 2, shape: 'square', status: 'occupied', currentOrderId: 'ord-1001', posX: 80, posY: 100, qrCodeToken: 'qr_tbl_m1_tok', assignedWaiterId: 'emp-waiter-1', minSpend: 100, lastOccupiedAt: NOW, createdAt: NOW, updatedAt: NOW },
  { id: 'tbl-m2', tableNumber: 'T-02', sectionId: 'sec-main', capacity: 4, shape: 'rectangle', status: 'available', posX: 220, posY: 100, qrCodeToken: 'qr_tbl_m2_tok', assignedWaiterId: 'emp-waiter-1', minSpend: 150, createdAt: NOW, updatedAt: NOW },
  { id: 'tbl-m3', tableNumber: 'T-03', sectionId: 'sec-main', capacity: 4, shape: 'rectangle', status: 'billing', currentOrderId: 'ord-1002', posX: 360, posY: 100, qrCodeToken: 'qr_tbl_m3_tok', assignedWaiterId: 'emp-waiter-2', minSpend: 150, lastOccupiedAt: NOW, createdAt: NOW, updatedAt: NOW },
  { id: 'tbl-m4', tableNumber: 'T-04', sectionId: 'sec-main', capacity: 6, shape: 'round', status: 'available', posX: 500, posY: 100, qrCodeToken: 'qr_tbl_m4_tok', minSpend: 250, createdAt: NOW, updatedAt: NOW },
  { id: 'tbl-m5', tableNumber: 'T-05', sectionId: 'sec-main', capacity: 8, shape: 'rectangle', status: 'reserved', posX: 80, posY: 260, qrCodeToken: 'qr_tbl_m5_tok', minSpend: 400, createdAt: NOW, updatedAt: NOW },

  { id: 'tbl-t1', tableNumber: 'TR-01', sectionId: 'sec-terrace', capacity: 4, shape: 'round', status: 'occupied', currentOrderId: 'ord-1003', posX: 80, posY: 120, qrCodeToken: 'qr_tbl_t1_tok', assignedWaiterId: 'emp-waiter-2', minSpend: 120, lastOccupiedAt: NOW, createdAt: NOW, updatedAt: NOW },
  { id: 'tbl-t2', tableNumber: 'TR-02', sectionId: 'sec-terrace', capacity: 4, shape: 'round', status: 'available', posX: 240, posY: 120, qrCodeToken: 'qr_tbl_t2_tok', minSpend: 120, createdAt: NOW, updatedAt: NOW },
  { id: 'tbl-t3', tableNumber: 'TR-03', sectionId: 'sec-terrace', capacity: 2, shape: 'square', status: 'cleaning', posX: 400, posY: 120, qrCodeToken: 'qr_tbl_t3_tok', minSpend: 80, createdAt: NOW, updatedAt: NOW },

  { id: 'tbl-v1', tableNumber: 'VIP-01', sectionId: 'sec-vip', capacity: 10, shape: 'rectangle', status: 'occupied', currentOrderId: 'ord-1004', posX: 120, posY: 140, qrCodeToken: 'qr_tbl_v1_tok', assignedWaiterId: 'emp-waiter-1', minSpend: 800, lastOccupiedAt: NOW, createdAt: NOW, updatedAt: NOW },
  { id: 'tbl-v2', tableNumber: 'VIP-02', sectionId: 'sec-vip', capacity: 12, shape: 'rectangle', status: 'available', posX: 380, posY: 140, qrCodeToken: 'qr_tbl_v2_tok', minSpend: 1000, createdAt: NOW, updatedAt: NOW },
];

// ==========================================
// 5. INVENTORY RAW ITEMS & SUPPLIERS
// ==========================================
export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-almarai-meat',
    nameAr: 'شركة المروج لتوريد اللحوم والمواشي البلدية',
    nameEn: 'Al-Morooj Prime Livestock & Meats Co.',
    contactPerson: 'الشيخ عبد الله الدوسري',
    phone: '+966501234567',
    email: 'orders@almoroojmeats.sa',
    taxNumber: '300123456700003',
    address: 'الرياض - حي الملز - شارع الظهران',
    paymentTerms: 'Net 30 Days',
    rating: 4.9,
    balance: 14500.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sup-fresh-produce',
    nameAr: 'مؤسسة خيرات القصيم للخضار والفواكه الطازجة',
    nameEn: 'Qassim Fresh Fruits & Vegetables Est.',
    contactPerson: 'فهد التميمي',
    phone: '+966559876543',
    email: 'supply@qassimfresh.sa',
    taxNumber: '300987654300003',
    address: 'القصيم - بريدة - سوق الجملة المركزي',
    paymentTerms: 'Weekly Cash',
    rating: 4.8,
    balance: 3200.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sup-dairy-imports',
    nameAr: 'شركة الأجبان والألبان الأوروبية الفاخرة',
    nameEn: 'Euro Gourmet Dairy & Cheese Ltd.',
    contactPerson: 'مارتن لوران',
    phone: '+966542233445',
    email: 'imports@eurodairy.com',
    taxNumber: '300765432100003',
    address: 'جدة - حي الأندلس - طريق الملك عبد العزيز',
    paymentTerms: 'Net 15 Days',
    rating: 4.7,
    balance: 8900.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'raw-wagyu-beef',
    code: 'RAW-BEEF-WAGYU',
    nameAr: 'لحم واغيو ياباني A5 مبرد',
    nameEn: 'Chilled Japanese A5 Wagyu Ribeye',
    category: 'اللحوم والدواجن',
    unit: 'kg',
    currentStock: 18.5,
    minStockAlert: 5.0,
    maxStock: 30.0,
    reorderQuantity: 15.0,
    averageCost: 380.0,
    lastPurchasePrice: 390.0,
    defaultSupplierId: 'sup-almarai-meat',
    storageLocation: 'مبرد اللحوم الفاخرة #1',
    expiryTracking: true,
    shelfLifeDays: 14,
    yieldRatio: 0.95,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'raw-local-lamb',
    code: 'RAW-LAMB-LOCAL',
    nameAr: 'لحم غنم نعيمي بلدي طازج بالعظم',
    nameEn: 'Fresh Local Naeemi Lamb on Bone',
    category: 'اللحوم والدواجن',
    unit: 'kg',
    currentStock: 45.0,
    minStockAlert: 15.0,
    maxStock: 80.0,
    reorderQuantity: 30.0,
    averageCost: 65.0,
    lastPurchasePrice: 66.0,
    defaultSupplierId: 'sup-almarai-meat',
    storageLocation: 'غرفة تبريد اللحوم الرئيسية',
    expiryTracking: true,
    shelfLifeDays: 5,
    yieldRatio: 0.82,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'raw-fresh-salmon',
    code: 'RAW-FISH-SALMON',
    nameAr: 'سمك سلمون نرويجي طازج كامل',
    nameEn: 'Fresh Norwegian Whole Salmon',
    category: 'الأسماك والمأكولات البحرية',
    unit: 'kg',
    currentStock: 14.0,
    minStockAlert: 6.0,
    maxStock: 25.0,
    reorderQuantity: 10.0,
    averageCost: 75.0,
    lastPurchasePrice: 78.0,
    defaultSupplierId: 'sup-dairy-imports',
    storageLocation: 'ثلاجة الأسماك 0-2C',
    expiryTracking: true,
    shelfLifeDays: 4,
    yieldRatio: 0.70,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'raw-burrata-cheese',
    code: 'RAW-DAIRY-BURRATA',
    nameAr: 'جبن بوراتا إيطالي طازج (كرات 125غ)',
    nameEn: 'Fresh Italian Burrata Cheese (125g balls)',
    category: 'الألبان والأجبان',
    unit: 'piece',
    currentStock: 48,
    minStockAlert: 12,
    maxStock: 80,
    reorderQuantity: 40,
    averageCost: 11.5,
    lastPurchasePrice: 12.0,
    defaultSupplierId: 'sup-dairy-imports',
    storageLocation: 'ثلاجة الأجبان والألبان',
    expiryTracking: true,
    shelfLifeDays: 10,
    yieldRatio: 1.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'raw-truffle-oil',
    code: 'RAW-OIL-TRUFFLE',
    nameAr: 'زيت الكمأة السوداء الإيطالي الأصيل',
    nameEn: 'Authentic Italian Black Truffle Oil',
    category: 'الزيوت والتوابل',
    unit: 'liter',
    currentStock: 6.5,
    minStockAlert: 2.0,
    maxStock: 12.0,
    reorderQuantity: 5.0,
    averageCost: 180.0,
    lastPurchasePrice: 185.0,
    defaultSupplierId: 'sup-dairy-imports',
    storageLocation: 'مستودع البهارات الجافة',
    expiryTracking: false,
    yieldRatio: 1.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'raw-basmati-rice',
    code: 'RAW-GRAIN-RICE',
    nameAr: 'أرز بسمتي هندي ملكي طويل الحبة',
    nameEn: 'Royal Indian Long Grain Basmati Rice',
    category: 'البقوليات والحبوب',
    unit: 'kg',
    currentStock: 120.0,
    minStockAlert: 30.0,
    maxStock: 250.0,
    reorderQuantity: 100.0,
    averageCost: 9.5,
    lastPurchasePrice: 9.2,
    defaultSupplierId: 'sup-fresh-produce',
    storageLocation: 'المخزن الجاف A',
    expiryTracking: false,
    yieldRatio: 2.2, // Expands when cooked
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'raw-akkawi-cheese',
    code: 'RAW-DAIRY-AKKAWI',
    nameAr: 'جبن عكاوي بلدي قليل الملوحة للكنافة',
    nameEn: 'Fresh Akkawi Cheese for Pastry',
    category: 'الألبان والأجبان',
    unit: 'kg',
    currentStock: 22.0,
    minStockAlert: 8.0,
    maxStock: 40.0,
    reorderQuantity: 20.0,
    averageCost: 32.0,
    lastPurchasePrice: 32.5,
    defaultSupplierId: 'sup-dairy-imports',
    storageLocation: 'ثلاجة الحلويات',
    expiryTracking: true,
    shelfLifeDays: 12,
    yieldRatio: 0.98,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'raw-passion-fruit',
    code: 'RAW-FRUIT-PASSION',
    nameAr: 'لب فاكهة الباشن فروت الطبيعي المجمد',
    nameEn: 'Frozen Natural Passion Fruit Pulp',
    category: 'الفواكه والعصائر',
    unit: 'liter',
    currentStock: 16.0,
    minStockAlert: 5.0,
    maxStock: 30.0,
    reorderQuantity: 15.0,
    averageCost: 28.0,
    lastPurchasePrice: 28.0,
    defaultSupplierId: 'sup-fresh-produce',
    storageLocation: 'فريزر البار -18C',
    expiryTracking: true,
    shelfLifeDays: 90,
    yieldRatio: 1.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ==========================================
// 6. RECIPES & INGREDIENT LINKS
// ==========================================
export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec-wagyu-steak',
    menuItemId: 'item-wagyu-ribeye',
    portionYield: 1,
    preparationMethodAr: 'تتبيل شريحة الواغيو بملح البحر الخشن، الشواء على نار عالية 2.5 دقيقة لكل وجه، الراحة 5 دقائق مع زبدة الكمأة',
    preparationMethodEn: 'Season with flaky sea salt, sear 2.5 min each side on high heat, rest 5 min topped with truffle butter',
    laborCostEstimate: 12.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'rec-royal-kunafa',
    menuItemId: 'item-royal-kunafa',
    portionYield: 1,
    preparationMethodAr: 'فرك عجينة الكنافة بالسمن البلدي، حشوها بالجبن العكاوي المنقوع، الخبز حتى الاحمرار وسكب القطر الساخن',
    preparationMethodEn: 'Toss phyllo dough with clarified ghee, fill with soaked cheese, bake to golden perfection and drizzle hot syrup',
    laborCostEstimate: 4.0,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const INITIAL_RECIPE_INGREDIENTS: RecipeIngredient[] = [
  { id: 'recing-1', recipeId: 'rec-wagyu-steak', inventoryItemId: 'raw-wagyu-beef', quantity: 0.32, unit: 'kg', wastePercentage: 6.0, costContribution: 121.6, createdAt: NOW, updatedAt: NOW },
  { id: 'recing-2', recipeId: 'rec-wagyu-steak', inventoryItemId: 'raw-truffle-oil', quantity: 0.015, unit: 'liter', wastePercentage: 2.0, costContribution: 2.7, createdAt: NOW, updatedAt: NOW },
  { id: 'recing-3', recipeId: 'rec-royal-kunafa', inventoryItemId: 'raw-akkawi-cheese', quantity: 0.18, unit: 'kg', wastePercentage: 3.0, costContribution: 5.76, createdAt: NOW, updatedAt: NOW },
];

// ==========================================
// 7. EMPLOYEES & STAFF
// ==========================================
export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-admin',
    employeeCode: 'EMP-001',
    firstName: 'طارق',
    lastName: 'المنصور',
    role: 'admin',
    pinCodeHash: '1234', // In production hashed, for preview/demo 1234
    phone: '+966500000001',
    email: 'admin@restaurantos.sa',
    nationalId: '1098765432',
    hourlyRate: 85.0,
    monthlySalary: 18000.0,
    employmentType: 'full_time',
    isActive: true,
    permissions: ['all'],
    hireDate: '2023-01-01',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'emp-manager',
    employeeCode: 'EMP-002',
    firstName: 'سارة',
    lastName: 'العنزي',
    role: 'manager',
    pinCodeHash: '2026',
    phone: '+966500000002',
    email: 'sara.manager@restaurantos.sa',
    nationalId: '1098765433',
    hourlyRate: 55.0,
    monthlySalary: 12000.0,
    employmentType: 'full_time',
    isActive: true,
    permissions: ['pos.*', 'inventory.*', 'employees.*', 'reports.*'],
    hireDate: '2023-06-15',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'emp-cashier-1',
    employeeCode: 'EMP-003',
    firstName: 'أحمد',
    lastName: 'الشريف',
    role: 'cashier',
    pinCodeHash: '1111',
    phone: '+966500000003',
    email: 'ahmed.pos@restaurantos.sa',
    nationalId: '1098765434',
    hourlyRate: 30.0,
    monthlySalary: 6000.0,
    employmentType: 'full_time',
    isActive: true,
    permissions: ['pos.orders', 'pos.payment', 'pos.split', 'pos.refund'],
    hireDate: '2024-02-01',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'emp-waiter-1',
    employeeCode: 'EMP-004',
    firstName: 'خالد',
    lastName: 'الغامدي',
    role: 'waiter',
    pinCodeHash: '2222',
    phone: '+966500000004',
    nationalId: '1098765435',
    hourlyRate: 25.0,
    monthlySalary: 5000.0,
    employmentType: 'full_time',
    isActive: true,
    permissions: ['pos.orders', 'tables.manage'],
    hireDate: '2024-04-10',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'emp-waiter-2',
    employeeCode: 'EMP-005',
    firstName: 'نورة',
    lastName: 'القحطاني',
    role: 'waiter',
    pinCodeHash: '3333',
    phone: '+966500000005',
    nationalId: '1098765436',
    hourlyRate: 25.0,
    monthlySalary: 5000.0,
    employmentType: 'full_time',
    isActive: true,
    permissions: ['pos.orders', 'tables.manage'],
    hireDate: '2024-05-01',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'emp-chef-1',
    employeeCode: 'EMP-006',
    firstName: 'الشيف جان مارك',
    lastName: 'بيليه',
    role: 'chef',
    pinCodeHash: '4444',
    phone: '+966500000006',
    nationalId: '2098765437',
    hourlyRate: 65.0,
    monthlySalary: 14000.0,
    employmentType: 'full_time',
    isActive: true,
    permissions: ['kds.manage', 'inventory.view', 'recipes.view'],
    hireDate: '2023-03-01',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=200&q=80',
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ==========================================
// 8. CUSTOMERS & LOYALTY
// ==========================================
export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-vip-1',
    customerCode: 'VIP-7701',
    name: 'سعادة عبد العزيز آل الشيخ',
    phone: '+966505551122',
    email: 'abdulaziz@vip-guest.sa',
    address: 'الرياض - حي النخيل الغربي - فيلا 42',
    deliveryZone: 'شمال الرياض',
    totalSpent: 18450.0,
    totalOrders: 32,
    loyaltyPoints: 1845,
    tier: 'vip',
    birthDate: '1984-07-22',
    notes: 'يفضل دائمًا طاولة VIP-01 والستيك مطهو Medium Rare مع مشروب V60 ساخن',
    favoriteItems: ['item-wagyu-ribeye', 'item-v60-coffee', 'item-truffle-tagliatelle'],
    isBlacklisted: false,
    lastOrderAt: NOW,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cust-gold-2',
    customerCode: 'CUST-3320',
    name: 'د. ليلى السبيعي',
    phone: '+966541122334',
    email: 'dr.layla@hospital.sa',
    address: 'الرياض - حي حطين - مجمع الرائدة',
    deliveryZone: 'حطين والنرجس',
    totalSpent: 4320.0,
    totalOrders: 14,
    loyaltyPoints: 432,
    tier: 'gold',
    notes: 'حساسية شديدة من الفول السوداني، تفضل التراس الخارجي',
    favoriteItems: ['item-dynamite-shrimp', 'item-grilled-salmon', 'item-passion-mojito'],
    isBlacklisted: false,
    lastOrderAt: NOW,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cust-silver-3',
    customerCode: 'CUST-1198',
    name: 'م. حسام الشهري',
    phone: '+966567788990',
    email: 'hussam.eng@gmail.com',
    totalSpent: 1280.0,
    totalOrders: 5,
    loyaltyPoints: 128,
    tier: 'silver',
    isBlacklisted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ==========================================
// 9. COUPONS & PROMOTIONS
// ==========================================
export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-welcome20',
    code: 'WELCOME20',
    descriptionAr: 'خصم 20% ترحيبي للعملاء الجدد',
    descriptionEn: '20% Welcome discount on first visit',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 100.0,
    maxDiscount: 50.0,
    validFrom: '2026-01-01T00:00:00Z',
    validUntil: '2026-12-31T23:59:59Z',
    usageLimit: 1000,
    currentUsageCount: 84,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'coup-vip50',
    code: 'VIP50',
    descriptionAr: 'خصم 50 ريال فوري على الطلبات فوق 300 ريال',
    descriptionEn: 'SAR 50 Flat Discount on Orders above SAR 300',
    discountType: 'fixed',
    discountValue: 50,
    minOrderValue: 300.0,
    validFrom: '2026-01-01T00:00:00Z',
    validUntil: '2026-12-31T23:59:59Z',
    usageLimit: 500,
    currentUsageCount: 42,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ==========================================
// 10. CURRENT SHIFT & CASH DRAWER
// ==========================================
export const INITIAL_SHIFT: Shift = {
  id: 'shift-current-01',
  shiftNumber: 'SH-20260814-01',
  employeeId: 'emp-cashier-1',
  role: 'cashier',
  startedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  openingCash: 1500.0,
  expectedCash: 3450.0,
  totalSales: 4120.0,
  totalCashSales: 1950.0,
  totalCardSales: 2170.0,
  totalDiscounts: 80.0,
  totalRefunds: 0.0,
  orderCount: 18,
  guestCount: 42,
  status: 'open',
  notes: 'شيفت الفترة المسائية - الصالة ممتلئة بنسبة 85%',
  createdAt: NOW,
  updatedAt: NOW,
};

export const INITIAL_CASH_DRAWER: CashDrawer = {
  id: 'drawer-01',
  shiftId: 'shift-current-01',
  openedBy: 'emp-cashier-1',
  openingCash: 1500.0,
  currentCash: 3450.0,
  expectedCash: 3450.0,
  status: 'open',
  openedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  createdAt: NOW,
  updatedAt: NOW,
};

// ==========================================
// 11. ACTIVE SAMPLE ORDERS (FOR POS & KDS PREVIEWS)
// ==========================================
export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'ORD-20260814-001',
    dailySequence: 1,
    orderType: 'dine_in',
    tableId: 'tbl-m1',
    customerId: 'cust-silver-3',
    waiterId: 'emp-waiter-1',
    cashierId: 'emp-cashier-1',
    status: 'preparing',
    paymentStatus: 'unpaid',
    subtotal: 213.04,
    taxAmount: 31.96,
    discountAmount: 0,
    serviceCharge: 0,
    tipAmount: 0,
    deliveryFee: 0,
    totalAmount: 245.0,
    paidAmount: 0,
    changeAmount: 0,
    guestCount: 2,
    customerNotes: 'الرجاء تقليل الملح في الشوربة',
    syncStatus: 'synced',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: NOW,
  },
  {
    id: 'ord-1002',
    orderNumber: 'ORD-20260814-002',
    dailySequence: 2,
    orderType: 'dine_in',
    tableId: 'tbl-m3',
    customerId: 'cust-gold-2',
    waiterId: 'emp-waiter-2',
    cashierId: 'emp-cashier-1',
    status: 'ready',
    paymentStatus: 'unpaid',
    subtotal: 265.22,
    taxAmount: 39.78,
    discountAmount: 20.0,
    discountType: 'coupon',
    serviceCharge: 0,
    tipAmount: 15.0,
    deliveryFee: 0,
    totalAmount: 300.0,
    paidAmount: 0,
    changeAmount: 0,
    guestCount: 3,
    syncStatus: 'synced',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updatedAt: NOW,
  },
  {
    id: 'ord-1004',
    orderNumber: 'ORD-20260814-004',
    dailySequence: 4,
    orderType: 'dine_in',
    tableId: 'tbl-v1',
    customerId: 'cust-vip-1',
    waiterId: 'emp-waiter-1',
    cashierId: 'emp-cashier-1',
    status: 'sent_to_kitchen',
    paymentStatus: 'unpaid',
    subtotal: 730.43,
    taxAmount: 109.57,
    discountAmount: 50.0,
    discountType: 'fixed',
    serviceCharge: 0,
    tipAmount: 50.0,
    deliveryFee: 0,
    totalAmount: 840.0,
    paidAmount: 0,
    changeAmount: 0,
    guestCount: 6,
    customerNotes: 'طاولة VIP - خدمة سريعة واهتمام خاص',
    syncStatus: 'synced',
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updatedAt: NOW,
  },
];

export const INITIAL_ORDER_ITEMS: OrderItem[] = [
  // Items for Order 1001 (Table M1)
  {
    id: 'orditem-1',
    orderId: 'ord-1001',
    menuItemId: 'item-mixed-mezze',
    nameAr: 'تشكيلة المزة الشامية الملكية',
    nameEn: 'Royal Levantine Mezze Platter',
    quantity: 1,
    unitPrice: 68.0,
    costPrice: 18.5,
    subtotal: 59.13,
    taxAmount: 8.87,
    discountAmount: 0,
    totalAmount: 68.0,
    selectedModifiers: [],
    kitchenStation: 'salad_cold',
    status: 'served',
    printedToKitchen: true,
    firedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    readyAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    servedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'orditem-2',
    orderId: 'ord-1001',
    menuItemId: 'item-mixed-grill-platter',
    nameAr: 'مشكل مشاوي السلطان المميز',
    nameEn: 'Sultan Special Mixed Grill Platter',
    quantity: 1,
    unitPrice: 145.0,
    costPrice: 48.0,
    subtotal: 126.09,
    taxAmount: 18.91,
    discountAmount: 0,
    totalAmount: 145.0,
    selectedModifiers: [
      { optionId: 'opt-peppercorn-sauce', groupId: 'mod-sauces', nameAr: 'صلصة الفلفل الأسود', nameEn: 'Peppercorn Sauce', price: 8.0, quantity: 1 }
    ],
    kitchenStation: 'grill',
    status: 'cooking',
    printedToKitchen: true,
    firedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    cookingStartedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'orditem-3',
    orderId: 'ord-1001',
    menuItemId: 'item-passion-mojito',
    nameAr: 'موهيتو الباشن فروت والنعناع المنعش',
    nameEn: 'Passion Fruit & Fresh Mint Artisan Mojito',
    quantity: 1,
    unitPrice: 34.0,
    costPrice: 6.0,
    subtotal: 29.57,
    taxAmount: 4.43,
    discountAmount: 0,
    totalAmount: 34.0,
    selectedModifiers: [],
    kitchenStation: 'beverages',
    status: 'served',
    printedToKitchen: true,
    firedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    readyAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    servedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    createdAt: NOW,
    updatedAt: NOW,
  },

  // Items for Order 1004 (VIP Table)
  {
    id: 'orditem-4',
    orderId: 'ord-1004',
    menuItemId: 'item-wagyu-ribeye',
    nameAr: 'ستيك واغيو ريب آي (درجة A5)',
    nameEn: 'Japanese Wagyu Ribeye Steak A5',
    quantity: 2,
    unitPrice: 320.0,
    costPrice: 125.0,
    subtotal: 556.52,
    taxAmount: 83.48,
    discountAmount: 0,
    totalAmount: 640.0,
    selectedModifiers: [
      { optionId: 'opt-medium-rare', groupId: 'mod-steak-doneness', nameAr: 'Medium Rare', nameEn: 'Medium Rare', price: 0, quantity: 1 },
      { optionId: 'opt-truffle-butter', groupId: 'mod-sauces', nameAr: 'زبدة الكمأة', nameEn: 'Truffle Butter', price: 14.0, quantity: 1 }
    ],
    kitchenStation: 'grill',
    status: 'pending',
    printedToKitchen: true,
    firedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'orditem-5',
    orderId: 'ord-1004',
    menuItemId: 'item-truffle-tagliatelle',
    nameAr: 'تاليياتيلي الكمأة البرية وجبن البارميزان',
    nameEn: 'Fresh Black Truffle Tagliatelle',
    quantity: 2,
    unitPrice: 95.0,
    costPrice: 26.0,
    subtotal: 165.22,
    taxAmount: 24.78,
    discountAmount: 0,
    totalAmount: 190.0,
    selectedModifiers: [],
    kitchenStation: 'bakery',
    status: 'pending',
    printedToKitchen: true,
    firedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    createdAt: NOW,
    updatedAt: NOW,
  },
];

// ==========================================
// 12. SYSTEM DEFAULT SETTINGS
// ==========================================
export const INITIAL_SETTINGS: SettingRecord[] = [
  { id: 'set-rest-name-ar', key: 'restaurant_name_ar', value: 'مطعم السلطان الفاخر للمأكولات الملكية', group: 'restaurant', description: 'اسم المطعم بالعربية', createdAt: NOW, updatedAt: NOW },
  { id: 'set-rest-name-en', key: 'restaurant_name_en', value: 'Sultan Royal Fine Dining Restaurant', group: 'restaurant', description: 'Restaurant Name in English', createdAt: NOW, updatedAt: NOW },
  { id: 'set-tax-number', key: 'tax_registration_number', value: '300987654300003', group: 'tax', description: 'الرقم الضريبي للمنشأة', createdAt: NOW, updatedAt: NOW },
  { id: 'set-vat-rate', key: 'default_vat_rate', value: 0.15, group: 'tax', description: 'نسبة ضريبة القيمة المضافة 15%', createdAt: NOW, updatedAt: NOW },
  { id: 'set-currency', key: 'currency_code', value: 'SAR', group: 'pos', description: 'العملة الأساسية (ريال سعودي)', createdAt: NOW, updatedAt: NOW },
  { id: 'set-city', key: 'restaurant_city', value: 'Riyadh', group: 'restaurant', description: 'مدينة المطعم لحساب الطقس', createdAt: NOW, updatedAt: NOW },
  { id: 'set-lat', key: 'restaurant_latitude', value: 24.7136, group: 'restaurant', description: 'خط العرض الجغرافي للمطعم', createdAt: NOW, updatedAt: NOW },
  { id: 'set-lng', key: 'restaurant_longitude', value: 46.6753, group: 'restaurant', description: 'خط الطول الجغرافي للمطعم', createdAt: NOW, updatedAt: NOW },
  { id: 'set-ai-provider', key: 'ai_primary_provider', value: 'google-ai', group: 'ai', description: 'المزود الأساسي للذكاء الاصطناعي', createdAt: NOW, updatedAt: NOW },
  { id: 'set-ai-fallback', key: 'ai_fallback_provider', value: 'openrouter', group: 'ai', description: 'مزود الذكاء الاصطناعي الاحتياطي', createdAt: NOW, updatedAt: NOW },
  { id: 'set-zatca-mode', key: 'zatca_integration_mode', value: 'simulation', group: 'tax', description: 'وضع ربط هيئة الزكاة والضريبة والجمارك (ZATCA)', createdAt: NOW, updatedAt: NOW },
  { id: 'set-receipt-footer-ar', key: 'receipt_footer_ar', value: 'شكرًا لزيارتكم الكريمة - نسعد بخدمتكم دائمًا', group: 'printer', description: 'تذييل الفاتورة المطبوعة', createdAt: NOW, updatedAt: NOW },
];
